### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by sinedoOo** [negativo17/mpv#1]
I have found some information about mpv's Wayland support on page https://wayland.freedesktop.org/extras.html ("--disable-x11 --disable-sdl --enable-wayland --disable-libass"). Current build from your repo doesn't work well on Wayland (no window controls, can't quit gui). Is there any way to add another package, for example "mpv-wayland" that's build specially for Wayland? I'm really newbe, so sorry if this desn't make any sense.

**Comment by scaronni** [comment]
Hello, Wayland support is already enabled:

```
Checking for Wayland                                                      : yes 
Checking for OpenGL Wayland Backend                                       : yes 
Checking for VAAPI (Wayland support)                                      : yes
```

What command line are you using to enable the Wayland backend? I see a few issues opened upstream regarding the Wayland backend.

**Comment by scaronni** [comment]
Closing, no reply.
