### ISSUE TITLE
Mpv update for EL7

### ISSUE THREAD

**Issue by hubslave** [negativo17/mpv#10]
Hello,

Please is there any chance you could update MPV for Enterprise Linux 7 to ver. 28.2? There are few new features and CVEs mitigations.

Thank you very much for any reply and have a nice day :)

**Comment by scaronni** [comment]
Hello, MPV 0.28.2 requires an unreleased FFMpeg. I will update it to that version once the new FFMpeg is released.

In the meanwhile, I've updated to 0.27.2, which contains the same CVE fixes.
