### ISSUE TITLE
Compile mpv with Vulkan support

### ISSUE THREAD

**Issue by jp7677** [negativo17/mpv#11]
Hi there, 

mpv 0.28 has gained support Vulkan as GPU-context. Would be cool to have it compiled with support for it.

```
./waf configure --help

 video outputs:
    --disable-vulkan    disable Vulkan context support [autodetect]
```

I guess just adding a dependency to vulkan (vulkan-devel) should do the trick.

With current mpv build you'll see:
```
mpv --gpu-api=help
GPU APIs (contexts):
    auto (autodetect)
    opengl (x11probe)
    opengl (x11egl)
    opengl (x11)
    opengl (drm)
    opengl (vdpauglx)
```

When mpv is compiled with Vulkan support it should be something like:
```
mpv --gpu-api=help
GPU APIs (contexts):
    auto (autodetect)
    opengl (x11probe)
    opengl (x11egl)
    opengl (x11)
    opengl (wayland)
    vulkan (waylandvk)
    vulkan (x11vk)
```

PS: I haven't really paid attention to to wayland, I'm seeing that additional context in my local mpv build too. I guess it's just another dependency.

**Comment by jp7677** [comment]
Regarding wayland, I found these lines in my mpv config.log 
```
-----------------------------------------------------------------
Checking for wayland-scanner
find program=['wayland-scanner'] paths=['/usr/lib64/qt-3.3/bin', '/usr/share/Modules/bin', '/usr/local/bin', '/usr/local/sbin', '/usr/bin', '/usr/sbin', '/home/jpeters/.local/bin', '/home/jpeters/bin'] var='WAYSCAN' -> ['/usr/bin/wayland-scanner']
yes
-----------------------------------------------------------------
Checking for wayland-protocols
['/usr/bin/pkg-config', 'wayland-protocols >= 1.12', '--variable=pkgdatadir', 'wayland-protocols']
out: //usr/share/wayland-protocols //usr/share/wayland-protocols

yes
-----------------------------------------------------------------
Checking for Wayland
['/usr/bin/pkg-config', 'wayland-client >= 1.6.0', 'wayland-cursor >= 1.6.0', 'xkbcommon >= 0.3.0', '--libs', '--cflags', 'wayland-client', 'wayland-cursor', 'xkbcommon']
out: -lwayland-client -lwayland-cursor -lxkbcommon 

yes
-----------------------------------------------------------------
```
The spec does not list `wayland-protocols` as dependency (https://github.com/negativo17/mpv/blob/master/mpv.spec#L76). I guess this one is missing for wayland support. Should I create a PR or edit the referred one for that dependency too?

**Comment by scaronni** [comment]
Yes please! Just make one PR with all the improvements you would like to see.

Thanks!

**Comment by jp7677** [comment]
Done, should be fine now.

**Comment by scaronni** [comment]
Pushed to the repositories, thanks.

**Comment by jp7677** [comment]
```
mpv --gpu-api=help
GPU APIs (contexts):
    auto (autodetect)
    opengl (x11probe)
    opengl (x11egl)
    opengl (x11)
    opengl (wayland)
    opengl (drm)
    opengl (vdpauglx)
    vulkan (waylandvk)
    vulkan (x11vk)
```

Confirmed, everything is there, thanks a lot!

**Comment by juxi500** [comment]
May I just ask out of curiosity - Is there some advantage when running mpv in vulkan mode?

**Comment by jp7677** [comment]
@juxi500 I'm not that much of an expert of how mpv uses OpenGL or Vulkan. I guess unless you are doing some fancy filtering with shaders there is currently no really visible practical advantage of Vulkan to OpenGL. That said, it feels good to use a modern GPU-API ;).

**Comment by juxi500** [comment]
Thank you very much @jp7677

I tried to run `mpv --gpu-api=help` on my EL7 machine but I don't see vulkan API there, should it work on EL7 too?

**Comment by jp7677** [comment]
@juxi500 Sorry, the Wayland and Vulkan dependencies are only enabled when compiling for Fedora.
See https://github.com/negativo17/mpv/blob/master/mpv.spec#L75

**Comment by scaronni** [comment]
I guess we can probably enable those also on RHEL. I'll look into that.

**Comment by scaronni** [comment]
I mean, Vulkan + X11.

**Comment by scaronni** [comment]
@juxi500 I have an EL7 build with Vulkan enabled. No Wayland, as the support for it in EL7 is not complete and does not even build.

https://github.com/negativo17/mpv/commit/fba8c66d00891e70ca06e056a88c59f3b0711c14

Can you try it? It's in the repository folder but out of the metadata, so you must explicitly install it manually:
```
# rpm -Uvh https://negativo17.org/repos/multimedia/epel-7/x86_64/mpv-0.28.2-3.el7.x86_64.rpm
```
If it works fine for you, I will add it to the metadata.

**Comment by juxi500** [comment]
Hello @scaronni, thank you very much :) Today I tested it, everything is working fine except when going to fullscreen - when you go to fullscreen when using vulkan api, mpv's image freezes while audio keeps on playing. In the end I have to shut down mpv.

I also get these errors in console:
[vo/gpu/vulkan] vkQueuePresentKHR(queue, &pinfo): VK_ERROR_OUT_OF_DATE_KHR
[vo/gpu] Failed presenting frame!

**Comment by jp7677** [comment]
Hi @juxi500 
I'm seeing the same behavior on Fedora. Try to repeatedly switch between full-screen and window mode, sometimes it works. I guess this is an issue in mpv itself and will be resolved with a future version.

**Comment by scaronni** [comment]
Pushed.
