### ISSUE TITLE
mpv 0.29

### ISSUE THREAD

**Issue by juxi500** [negativo17/mpv#13]
Hello,

I just wanted to let you know that mpv 0.29 was released:

https://github.com/mpv-player/mpv/releases/tag/v0.29.0

No need to hurry, but if you had some free time on your hands in the future, I'm sure that multiple users of your repo (including me) will be happy to see it :)

Thank you very much for all your effort and have a nice day :)

**Comment by scaronni** [comment]
Coming soon in a few hours at the next repository refresh:
https://github.com/negativo17/mpv/commit/700d5685145808bb7c3b5e713ceb29797adfa6f0

**Comment by juxi500** [comment]
Works great! Thank you very much :) Now it is even possible to use mpv with Vulkan backend without getting freezes in full-screen mode :)
