### ISSUE TITLE
vulkan backend not working anymore on el7.6

### ISSUE THREAD

**Issue by juxi500** [negativo17/mpv#15]
hello,

I tried to use mpv with vulkan backend on el7.6, but I get these errors:

`[vo/gpu/vulkan] Failed initializing SPIR-V compiler!`
`[vo/gpu] Failed initializing any suitable GPU context!`
`Error opening/initializing the selected video_out (--vo) device.`
`Video: no video`

`Exiting... (Errors when loading file)`

I did not use vulkan backend for a while, but few months ago it was working.

Maybe it is caused by this [this](https://github.com/mpv-player/mpv/issues/6124) issue?

**Comment by juxi500** [comment]
Oh I just found out that you already resolved [this](https://github.com/negativo17/mpv/pull/14) issue on Fedora. Since el7.6 updated vulkan package to version 1.1.73, do you think it would be possible to have vulkan backend also working on el7.6?

**Comment by scaronni** [comment]
Sorry for the delay, had a tough time at work. I've requested `shaderc` branches for both `epel7` and `epel8`. I will make sure that `mpv` will require those as well on RHEL/CentOS.

**Comment by scaronni** [comment]
No chance to update these components in epel, too many dependencies unmet.
