### ISSUE TITLE
Enable vaporsync support

### ISSUE THREAD

**Issue by CarlosEkisde** [negativo17/mpv#16]
Hi, I'd be very pleased if support for vapoursynth is added. It's neccesary to be able to run mpv with SVP. Thank you!

**Comment by scaronni** [comment]
I've posted `vapoursynth` for review to Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1791588

In the meanwhile I'm adding the package to the repository and enable support for it: https://github.com/negativo17/vapoursynth

**Comment by scaronni** [comment]
Package will be online in a few hours.
