### ISSUE TITLE
mpv does not run

### ISSUE THREAD

**Issue by nerijus** [negativo17/mpv#2]
ffmpeg and mpv were just updated, but mpv does not run:
$ mpv
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.100 (runtime 57.64.101)
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.1

mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.

mpv does not support this configuration and will not run - rebuild mpv instead.

**Comment by nerijus** [comment]
mpv-0.22.0-1.fc25.x86_64
ffmpeg-3.2.1-1.fc25.x86_64

**Comment by scaronni** [comment]
Funny, I didn't know that MPV would complain in such a situation, because it links the shared libraries with only the major version as any other program. In fact all libraries are correctly found:

<pre lang="bash">$ ldd /usr/bin/mpv | grep libav
        libavutil.so.55 => /lib64/libavutil.so.55 (0x00007f65a8525000)
        libavcodec.so.57 => /lib64/libavcodec.so.57 (0x00007f65a7144000)
        libavformat.so.57 => /lib64/libavformat.so.57 (0x00007f65a6d4e000)
        libavfilter.so.6 => /lib64/libavfilter.so.6 (0x00007f65a3ee5000)
        libavdevice.so.57 => /lib64/libavdevice.so.57 (0x00007f65a1367000)
        libavresample.so.3 => /lib64/libavresample.so.3 (0x00007f659718d000)</pre>

Will trigger a rebuild immediately. Thanks for reporting.

**Comment by scaronni** [comment]
Pushed.
