### ISSUE TITLE
MPV can't launch in Fedora 25

### ISSUE THREAD

**Issue by AdelKS** [negativo17/mpv#3]
Hello !

Thank you very much for your work on offering GPU hardware acceleration for video encoding/decoding.
I have a little problem running MPV since I upgraded to Fedora 25 (from 24). I am sure it's something linked to rpm-fusion and fedora-HandBrake repos being both installed during the upgrade. I tried to reinstall MPV dependencies by only enabling fedora-Handbrake but it did not work:

`dnf reinstall $(dnf repoquery --requires --resolve mpv) --disablerepo=rpmfusion* --disablerepo=fedora --disablerepo=updates --disablerepo=russian*
`

But I still get this:

> ffmpeg library versions:
>    libavutil       55.28.100 (runtime 55.34.100)
>    libavcodec      57.48.101 (runtime 57.64.101)
>    libavformat     57.41.100 (runtime 57.56.100)
>    libswscale      4.1.100 (runtime 4.2.100)
>    libavfilter     6.47.100 (runtime 6.65.100)
>    libswresample   2.1.100 (runtime 2.3.100)
> ffmpeg version: 3.2.1
> 
> mpv was compiled against a different version of FFmpeg/Libav than the shared
> library it is linked against. This is most likely a broken build and could
> result in misbehavior and crashes.
> 
> mpv does not support this configuration and will not run - rebuild mpv instead.

It seems that MPV needs newer versions of libraries, but I can't install them.
Do you have any idea in how I can correct this ?

Thanks!

**Comment by scaronni** [comment]
Oops, sorry, the fix was already commited but I forgot to mark the build for Fedora 25:

https://github.com/negativo17/mpv/commit/5b6746e344c68eff3d54a89279312cb10deb35b4

New build coming in a few minutes.

**Comment by scaronni** [comment]
Well, I did not build it, but I rebuild it before the change. I guess you're not using my MPV package. Can you print the version? I will bump the Epoch so it is not overwritten.

**Comment by AdelKS** [comment]
Hi !

I think I have found the problem by answering your question:

> [root@localhost Adel]# dnf reinstall mpv
> Last metadata expiration check: 0:01:19 ago on Tue Dec  6 11:53:51 2016.
> Dependencies resolved.
>
> Reinstalling:
>  mpv        x86_64        1:0.22.0-3.fc25         fedora-HandBrake        1.3 M
> 

But the version it says it has after reinstalling is:

> [root@localhost Adel]# mpv --version
> mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
>  built on Fri Sep  2 19:45:57 CEST 2016
> ffmpeg library versions:
>    libavutil       55.28.100 (runtime 55.34.100)
>    libavcodec      57.48.101 (runtime 57.64.101)
>    libavformat     57.41.100 (runtime 57.56.100)
>    libswscale      4.1.100 (runtime 4.2.100)
>    libavfilter     6.47.100 (runtime 6.65.100)
>    libswresample   2.1.100 (runtime 2.3.100)

It still thinks it's versuin 0.20. I am not sure that problem comes from you.
