### ISSUE TITLE
Enable DVB support

### ISSUE THREAD

**Issue by jp7677** [negativo17/mpv#7]
Hi there,

It seems that mpv >= 0.26 has DVB disabled by default, see https://github.com/mpv-player/mpv/releases/tag/v0.26.0

Since fedora usually has a modern kernel (and because dvb in mpv worked perfectly before on my machine), could you please consider to enable dvb in this negativo17 build?
Thanks and regards,
Jens

**Comment by jp7677** [comment]
This https://github.com/negativo17/mpv/pull/8 should do the trick.

**Comment by scaronni** [comment]
Updated the package with the flag. Can you make a test?

**Comment by jp7677** [comment]
Yes, will do. I guess the new package comes with a `dnf update --refresh`?

**Comment by scaronni** [comment]
You can delete the cache of the specific repository (`rm -fr /var/cache/dnf/fedora-multimedia*`), delete all DNF caches (`dnf clean all`) or just wait.

**Comment by scaronni** [comment]
Was it fixed?

**Comment by jp7677** [comment]
I tried `dnf clean all`, but it's not there yet.
(it should appear in https://negativo17.org/repos/multimedia/fedora-26/x86_64/  right?)

**Comment by scaronni** [comment]
Sorry, small problem when syncing repositories. Please retry.

**Comment by jp7677** [comment]
Thanks, will do today evening (CEST), I'm now at work.

**Comment by jp7677** [comment]
DVB works perfectly again, thanks a lot!
