### ISSUE TITLE
RFE: provide mplayer-backend

### ISSUE THREAD

**Issue by barsnick** [negativo17/mpv#9]
I'm using the rpmfusion and fedora-multimedia (negativo17) repos in parallel on F27. Yeah, bad choice maybe, but it has worked very fine all along. Thanks to your use of epochs, most stuff is pulled from fedora-multimedia, while I get things like kernel drivers and VirtualBox from rpmfusion.

Recently though, there has come a "minor" conflict, due to this situation:

I'm using smplayer from rpmfusion. smplayer can use mplayer or mpv as a "display engine", a.k.a. "backend". The smplayer package used to "Require" mplayer, yet rpmfusion smartly changed that to "mplayer-backend", which in turn is provided by both mplayer and mpv packages in their repo.

Due to a recent conflict of libx264 versions in these two repos (which will likely not go away before F28), I can no longer use mplayer or mpv from the rpmfusion repo. So fedora-multimedia's mpv would fit in great. Alas, it doesn't "Provide" mplayer-backend.

My request: Could you add "mplayer-backend" as a "Provides:" to the mpv package? It would resolve quite a bit of hassle. Thanks!

An alternative might be for fedora-multimedia to also package smplayer/smtube. ;-)

**Comment by leigh123linux** [comment]
I expect the conflicts to be much greater in F28 as rpmfusion we ship with newer ffmpeg, mpv and x265

> Due to a recent conflict of libx264 versions in these two repos (which will likely not go away before F28), I can no longer use mplayer or mpv from the rpmfusion repo. So fedora-multimedia's mpv would fit in great. Alas, it doesn't "Provide" mplayer-backend.

**Comment by scaronni** [comment]
@barsnick I can add `Provides: mplayer-backend`, it makes no difference for the package itself; I will add it to the next build.

But as you wrote here, if you need additional packages compared to what is in this repository you should definitely switch to RPMFusion.

**Comment by barsnick** [comment]
Thank you!

Yes, that's quite a conflict. You provide the nicer packages (newer, more dependencies provided and used, and so on). rpmfusion has a larger selection of tools.

I will probably try to clone negativo locally and build my own combination of packages (and added ones), for my personal needs. Only after I see what F28 brings. Negativo's newer packages have seldomly been a hindrance for the parallel use of the repos, until now.

Thanks for your efforts and the great repo(s).

**Comment by leigh123linux** [comment]
Currently rpmfusion has newer f28 packages than negativo17.
We have also released final f28 repo's, scaronni looks like he is in the process of doing a mass rebuild for ffmpeg-4.0

http://download1.rpmfusion.org/free/fedora/releases/28/Everything/x86_64/os/repoview/ 
http://download1.rpmfusion.org/nonfree/fedora/releases/28/Everything/x86_64/os/repoview/

> for my personal needs. Only after I see what F28 brings. Negativo's newer packages have seldomly been
